name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
   runs-on: ubuntu-lastet
   steps:
    - name: Autenticar no Docker Hub
      run: echo "Executando o comando Docker Login"
    - name: Construção da Imagem Docker
      run: echo "Executando o comando Docker build"
    - name: Envio da Imagem Docker
      run: echo "Executando o comando Docker push"

  cd:
   runs-on: ubuntu-lastet
   steps: 
    - name: Autenticar na AWS
      run: echo "Executando o comando aws configure"
    - name: Configurar o kubectl
      run: echo "Executando o comando aws eks update-kubeconfig"
    - name: Deploy dos manisfestos no kubernetes
      run: echo "Executando o comando kubeclt apply"
